### ISSUE TITLE
Repository New Version

### ISSUE THREAD

**Issue by themiguelamador** [BenLauwens/SimJulia.jl#15]
Is new version already available in Julia Repo?

**Comment by BenLauwens** [comment]
Hi Miguel

Not yet, I will finish the documentation and add some more examples by the end of the week. You can always use the current version of the repository as explained in the JuliaDoc.
Kind regards

Ben

**Comment by BenLauwens** [comment]
Hi

SimJulia v0.3.5 is tagged. Once the checks are done I can merge the pull request and you can Pkg.update()
Kind regards.

Ben
