### ISSUE TITLE
New BoundsError in tests

### ISSUE THREAD

**Issue by tkelman** [BenLauwens/SimJulia.jl#18]
Not sure if this is spurious, or if it was introduced by one of your dependencies changing something? Ref http://pkg.julialang.org/detail/SimJulia.html

**Comment by BenLauwens** [comment]
Hi

The error is introduced by a dependency. Compat or Distributions... 
I will look at it this evening
Kind regards

Ben

**Comment by BenLauwens** [comment]
It is definitely a problem with Compat.
@compat get(env.active_proc) gives the error.
I isolated the problem with following small example:

`using Compat

type Test
  a :: Float64
end

type TestCompat
  t :: @compat Nullable{Test}
  function TestCompat()
    tc = new()
    tc.t = @compat Nullable{Test}()
    return tc
  end
end

tc = TestCompat()
@compat get(tc.t)`

In Julia v0.4 without the @compat macro everything works fine (a NullException is thrown) but with the macro I get the following error message:
ERROR: LoadError: BoundsError: attempt to access 2-element Array{Any,1}:
 :get
 :(tc.t)
  at index [3]

I will open an issue at JuliaLang/Compat.jl

**Comment by BenLauwens** [comment]
I removed the @compat macro before get and this seems to work. A new version of SimJulia is tagged.
