### ISSUE TITLE
Bank Renege example minor bug

### ISSUE THREAD

**Issue by fbastin** [BenLauwens/SimJulia.jl#23]
In the example Bank Renege (http://simjuliajl.readthedocs.io/en/stable/examples/1_bank_renege.html), the line
cancel(counter, req)
does not work with the last version of SimJulia, and should be replaced by
cancel(req)

Note: I was not able to access the documentation on GitHub

**Comment by BenLauwens** [comment]
Hi

This is a bug in the documentation.
Thanks
