### ISSUE TITLE
Continuous Simulation

### ISSUE THREAD

**Issue by helgee** [BenLauwens/SimJulia.jl#24]
Hi Ben!

Is the continuous simulation part you presented at JuliaCon only available on the `continuous` branch right now?

**Comment by BenLauwens** [comment]
Hi

Yes ... I have rewritten the internals in the master branch to make the integration more easy but I am still trying to find out the best API for the definition of the the ODEs. I hope to have a new release end of January with everything integrated.

**Comment by helgee** [comment]
Great news! 👍
