### ISSUE TITLE
Output statistics?

### ISSUE THREAD

**Issue by xiaoweiz** [BenLauwens/SimJulia.jl#26]
This is perhaps a trivial question, but I couldn't figure out how to do it in an easy way. 

Take the Bank Renege example. I'd like to simulate 1000 customers and in the end obtain the mean waiting time as well as the frequency of reneging among the last 500 customers. How should I do it? In the documented example, the status of each customer is printed out. But I simply want some statistics output after the simulation is done. How should I do it?

**Comment by BenLauwens** [comment]
Hi

You can pass a common vector to all the processes to store output values. I know this can be a tricky and this is one of the things I will try to have a fixed way of doing this kind of stuff. I will release a new version once Julia v0.6 is released. This is one of the topics on my list;)
Kind regards

Ben

**Comment by BenLauwens** [comment]
Hi

I am working on this one ...
