### ISSUE TITLE
Using the @request macro in the Bank Renege example

### ISSUE THREAD

**Issue by ajkeith** [BenLauwens/SimJulia.jl#35]
First I'd like to say thanks for the very useful package!

I'm trying to follow along with the bank renege example from the documentation but it looks like that example code is a little behind the stable release (e.g., `@Process` vs `@process`). Once I fix those I get an error when the Request() block runs. I saw in some other comments that you're working on the documentation but I was wondering if you could point me to some more info on the `@request` macro (or if I should be using Request() ). 

Thanks!

**Comment by BenLauwens** [comment]
Hi

Sorry for the limited documentation;)
You can look at [processes_MM1.jl](https://github.com/BenLauwens/SimJulia.jl/blob/master/test/benchmarks/processes_MM1.jl) to have an example with `processes` (Julia `Tasks`) and the `request do` construct or you can look at [coroutines_MM1.jl](https://github.com/BenLauwens/SimJulia.jl/blob/master/test/benchmarks/coroutines_MM1.jl) for `coroutines` and the `@request` macro.
Replacing `Process` with `process` and `Request` with `request` would normally do the trick.
Kind regards

Ben

**Comment by ajkeith** [comment]
Thanks for the pointers!
