### ISSUE TITLE
SimJulia examples do not start

### ISSUE THREAD

**Issue by rbacher** [BenLauwens/SimJulia.jl#48]
In a julia 0.6.1 (win10) installation, after Pkg.add("SimJulia") and then using SimJulia, then defining
function car(env::Environment)
         while true
           println("Start parking at $(now(env))")
           parking_duration = 5.0
           yield(Timeout(env, parking_duration))
           println("Start driving at $(now(env))")
           trip_duration = 2.0
           yield(Timeout(env, trip_duration))
         end
       end
I am getting a ERROR message: UndefVarError: Environment is not defined.
Where is the problem with this very basic example?
Thanks
Rainer

**Comment by BenLauwens** [comment]
Hi

The Environment type is not exported in SimJulia v0.4.
Your example will work if you do a `Pkg.checkout("SimJulia")`. The master branch is feature complete and completely tested but only rudimentary documentation is available. I have planned to do a release early 2018.

Kind regards

Ben

**Comment by BenLauwens** [comment]
I have released a new version. Once `METADATA` is updated, I will close this issue.
