### ISSUE TITLE
ERROR: MethodError: no constructors have been defined for SimJulia.Environment

### ISSUE THREAD

**Issue by Okidoki72** [BenLauwens/SimJulia.jl#51]
Hi,

I'm trying to run the fist example from the section "SimJulia in 10 Minutes" on Julia v 0.6.2, and get the following error:

ERROR: MethodError: no constructors have been defined for SimJulia.Environment

Is there any compatibility problem with version 0.6.2?

Thanks in advance for the help!

**Comment by metanoid** [comment]
@Okidoki72 
I've seen this error before.  Am I correct in guessing you get the error when calling `Environment()`?  If so, try changing that to `Simulation()` - worked for me.

**Comment by Okidoki72** [comment]
Thank you so much for your help metanoid. Changing this line to Simulation() worked for me too. Unfortunately, I get a new error when calling `p = Process(env, example)` in the following line:

`env = Simulation()`
`p = Process(env, example)`
`run(env)`

Any idea?

**Comment by Okidoki72** [comment]
It seems that the documentation is not up to date. Instead of the function `Process(env, example)`, we should write `@process example(env)`.

**Comment by metanoid** [comment]
@Okidoki72 I think you can close this issue if you have found a solution
