### ISSUE TITLE
Make Store.items a dequeue 

### ISSUE THREAD

**Issue by riccardosven** [BenLauwens/SimJulia.jl#56]
Is there a specific reason why [`Store.items`] is a `Set{T}`?
In my opinion it makes for some counterintuitive behavior. For instance,
```
env = Simulation()
store = Store{Symbol}(env)
put(store, :apple)
put(store, :apple)
put(store, :pear)
```
gives
```
store.items
Set(Symbol[:pear, :apple])
```
which is counterintuitive as one would expect the store to contain two apples now; however, before making a pr, I wanted to know if there is some specific idea behind using `Set`.

[`Store.items`]:https://github.com/BenLauwens/SimJulia.jl/blob/1c9bf3f91c6abb1bd29a3a76a6547b9df350e09c/src/resources/stores.jl#L17

**Comment by BenLauwens** [comment]
Sorry for the late answer ... SimJulia had a low priority but it will be better in the future;)
A `Dequeue` is more logical. I will implement it.

**Comment by BenLauwens** [comment]
The problem with `Deque` is that it does not allow to delete an arbitrary element.
I have used a `Store` only with mutable objects. For immutable type we have that `a==b` is identical to `a===b`.
One way I can solve this, is boxing immutable types...

**Comment by hdavid16** [comment]
What is the path forward here?

**Comment by BenLauwens** [comment]
Boxing immutable objects or using a Dict with as key the object and as value the number of times it is stored. Both are doable. I have a slight preference for the latter. All input is welcome!

**Comment by hdavid16** [comment]
I definitely vote for the latter as well. I'm not a fan of boxing and using a dictionary would make it clear how many items you have.

**Comment by BenLauwens** [comment]
I had some spare time;) straightforward implementation of a Store based on a Dict is in the master branch.

julia```
julia> using SimJulia

julia> env = Simulation()
Simulation time: 0.0 active_process: nothing

julia> store = Store{Symbol}(env)
Store{Symbol}

julia> put(store, :apple)
SimJulia.Put 1

julia> put(store, :apple)
SimJulia.Put 2

julia> put(store, :pear)
SimJulia.Put 3

julia> store.items
Dict{Symbol, UInt64} with 2 entries:
  :pear  => 0x0000000000000001
  :apple => 0x0000000000000002
```

What do you think?

**Comment by hdavid16** [comment]
Looks great. I've started using this already. Unless you think it needs further work, I think we can close this issue.

**Comment by hdavid16** [comment]
I've been using this new implementation and it works great for my purposes. Unless @riccardosven suggests otherwise, we should close this issue.

**Comment by riccardosven** [comment]
I agree! Closed
