### ISSUE TITLE
LoadError: UndefVarError: active_proc not defined

### ISSUE THREAD

**Issue by zqubit** [BenLauwens/SimJulia.jl#62]
I see an error when using show(env).
Line 33 of base.jl
    print(io, "$(typeof(env)) time: $(now(env)) active_process: $(active_proc)")
should read
    print(io, "$(typeof(env)) time: $(now(env)) active_process: $(env.active_proc)")
instead?

**Comment by BenLauwens** [comment]
Thanks
Solved in master.
I will soon do a new release
