### ISSUE TITLE
Help with simple simulation loop

### ISSUE THREAD

**Issue by juliohm** [BenLauwens/SimJulia.jl#66]
Say I have a loop with simulations:

```Julia
# some expensive simulation
simulation(i) = sleep(i)

results = []
for i in 1:100
   push!(results,  simulation(i))
end
```

I've added a try-catch block to interrupt the loop if the user presses CTR+C:

```Julia
for i in 1:100
  try
     push!(results,  simulation(i))
  catch e
    e isa InterruptException && break
  end
end
```

Now I want to add another feature. Some of the simulations hang because they are too "difficult" to finish. I'd like to wait say 5min and if the simulation is still running, I would like to skip it in the loop. Can this package handle this use case? I am not familiar with discrete events, but it seems like it is a good approach? I am also open to Distributed solutions.

**Comment by hdavid16** [comment]
@juliohm what did you end up doing?

**Comment by juliohm** [comment]
I didn't find a solution yet @hdavid16. It seems that this feature requires multiple threads, one checking if the process is hanging. The language is still evolving to handle this case I guess.
