### ISSUE TITLE
Support for Discrete Time

### ISSUE THREAD

**Issue by tyhlee** [BenLauwens/SimJulia.jl#70]
Dear Ben:

I need to develop a simple discrete event simulation model for discrete time updates (e.g., monthly) without any consideration of resources. I am wondering if SimJulia can be configured to handle discrete time updates.

Thanks,
Tae Yoon Lee

**Comment by hdavid16** [comment]
Can you explain better what you are trying to do? Maybe with a small example. If you are trying to do a discrete time simulation on a uniform time grid, you may not need SimJulia. Furthermore, you can trigger events every month with the @yield macro inside a resumable function (e.g., @yield(env, t) where t is your event trigger time 1:12, but then again you don't need a discrete event simulation to do this).

**Comment by tyhlee** [comment]
Sure, for each agent I create, I want to run a set of events until the agent dies or reaches a pre-specified time limit. These event processes are updated at a fixed frequency (e.g., monthly) and dependent on each others. I will look into the yield macro. Thanks!

**Comment by hdavid16** [comment]
You could probably do this in a for loop iterating monthly. If you chose to use SimJulia, you can have an agent resource with the capacity being the number of agents that you have. Thus an agent is occupied as you run a process and released when the process completes. Feel free to reach out if you need any further help.

**Comment by hdavid16** [comment]
@tyhlee, I would also suggest you check out Agents.jl, which is more suited for discrete-time simulations. They also have GUI generation capabilities and many sample tutorials.

**Comment by BenLauwens** [comment]
Agents.jl is more suited for a specific kind of discrete-time simulations. Whatever is possible in Agents.jl can also be built in SimJulia.jl
